### ISSUE TITLE
Tombstone record Management

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-streams#198]
The Sink connector needs to manage the cancellation events on Kafka (tombstone record) which are made up of a valued key and a null value and that on "log retention compact" type topic types defines that the record with the provided key is deleted.

@vmantuano can you please share the configuration that you used in order to evaluate the Kafka connect Plugin?

Thanks a lot for the feedback!

**Comment by vmantuano** [comment]
Hi @conker84.
the configuration that I used for the test was:

- neo4j version 3.5.4
- kafka version 1.1.1 (confluent platform 4.1.1)

As I told you before, when I did the test (about a month ago), I used neo4j-streams software from the master branch because in the 3.5 version there was an error solved later  (fixes #162: Conversion error in case of nested field of array<Struct> …)

We used avro serialization in the input topic from which the neo4j sink connector polls messages

if you need more detail, let me know.
