### ISSUE TITLE
Provide a way to validate refuse data into ingestion strategies

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-streams#237]
We need to highlight into the ingestion strategy if the data is refused.
We can attach the `dead letter queue` mechanism in order to simplify the debug process.
Thanks @moxious for pointing this.

**Comment by moxious** [comment]
While you were away we merged this PR that's related to error handling, to try to centralize all error & DLQ handling.

https://github.com/neo4j-contrib/neo4j-streams/pull/231

A critical piece here is that error tolerance is now a configurable property of the plugin, and I think we've centralized that stuff.   This should be relevant to the way this issue is tackled.

There are several classes of when we'd want to refuse data:

- When it totally doesn't make sense.   I.e. CUD format is invalid, it isn't JSON, parse fails, is greater than some payload limitation size.
- When it does make sense, but fails some validation check.
- Something else?

I would advocate that each ingestion strategy should have some methods that perform validation on input, and then we always run those first and handle errors in a unified way before the ingestion strategy even gets a chance to consume the message.

We can then start with lightweight validation and improve it over time.   This should all be subject to the PR linked above.  So when validation fails, the error handling mechanism (tolerance, DLQ usage, etc) -- should all dictate what happens with that error.

**Comment by jexp** [comment]
Doesn't this happen automatically today if we raise an error?

There might be some places where we silently skip stuff?

**Comment by moxious** [comment]
I believe mostly we're not looking for or raising errors.  There may be some situations where if we're given bad data, it fails due to a bad assumption.  In these cases it might be hard to spot since you might end up with an exception down in the code that doesn't indicate data format.

Up-front validation and fast failing is better, IMHO
