### ISSUE TITLE
Source with non-existant topic hangs indefinitely

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-streams#252]
Will: If I configure Neo4j as a source for a topic that doesn’t exist in the kafka cluster, then any Cypher queries that would trigger publishing to this topic seem to hang. For example if I have

      streams.source.topic.nodes.fraudflags=Party{*}

but the topic I created in Kafka is fraud-flags instead of fraudflags then any Cypher queries that create or update a Party node just hang in Neo4j, presumable because the neo4j-streams plugin is unable to publish to a topic that doesn’t exist and needs to complete the publishing before the transaction can be closed. Is this the expected behavior? There was a DEBUG log message that neo4j-streams is trying to publish a transaction, which was enough to clue me in to investigate the cause of the hanging query but it might be nice to include which topic it is trying to publish to as well.

David: I’ve observed the same, but hadn’t looked into why it is yet.  I suspect what’s gonig on is that the client/transport layer accepts the message for delivery, and that what we’re perceiving as hanging is actually a message getting caught in a failure/retry loop within the Kafka driver.

**Comment by conker84** [comment]
Hi @johnymontana & @jexp 
Seems to be a bug, I found this inside the Kafka JIRA:
https://issues.apache.org/jira/browse/KAFKA-3539

My solution is to check at the startup for the broker config value `auto.create.topics.enable` which allows auto topic creation. If `false` we will check if the provided topics are already created inside the kafka cluster otherwise we return an exception and fail to start the streams plugin

/cc @moxious @mneedham

**Comment by moxious** [comment]
@conker84 I like that solution with one exception: don't fail to start the streams plugin, issue a disabled message and then continue on.  If I ask to produce to many topics, behavior is better if you disable the one that doesn't work and warn me loudly.  Partial functionality may be better than no functionality?

Also as per the previous issue about never crashing neo4j, always ensure that even if you're only producing to one topic and you can't even do that -- that it isn't a fatal error.  Disabling all functionality should be the worst case scenario.

**Comment by conker84** [comment]
I generally prefer a fail-fast approach because I want that the developer must be aware of what is happening. If we under-the-hood filter the topics, a busy developer can think that everything it's ok and afterwards discovers that he's missing data. But that's my 2 cents.

About the never crashing neo4j, this is under the configuration validation process, so the DB is not affected by that as it now happens for missing required parameters like `bootstrap.servers`.

Moreover, I thought about another scenario that could hang the DB:
1. The validation process it's ok
2. everything goes well until...
3. ...there is a `communication` problem between Neo4j and Kafka (i.e. network issues)

How we should deal with that? 

I did a PoC by wrapping this method inside a coroutine
https://github.com/neo4j-contrib/neo4j-streams/blob/248146efc2795abf522a6114955d7fab2e1c7f6c/producer/src/main/kotlin/streams/kafka/KafkaEventRouter.kt#L46-L52

And seems to work. WDYT? /cc @jexp 

And In case of exception how we should deal with the data?
1. Log it into the `neo4j.log` file?
2. Write it into a separate file?
3. Or?

**Comment by conker84** [comment]
@moxious @jexp ping

**Comment by moxious** [comment]
For now, errors basically have to be dealt with by logging alone, which gives the user a chance with downstream tooling to detect and intervene.

A second option I think we should consider is seeing if it's possible to plug into the Neo4j CSV metrics infrastructure.  Ideally we'd have a CSV data log of the messages and results we sent so that people could use the metrics features in Neo4j to monitor plugin performance.  Then the logs could be quite silent actually.
