### ISSUE TITLE
Allow to publish messages with key in Kafka topic

### ISSUE THREAD

**Issue by KavitaUnified** [neo4j-contrib/neo4j-streams#272]
## Allow to publish messages with key in Kafka topic.
Using streams.publish procedure add feature which will allow to publish message with key in Kafka topic. By adding this new feature we will be able to leverage all the advantages of having key in topic partitioning, order, log compaction, we can use the topic in joining multiple streams etc.

## Considered alternatives
As a work around we can write our own Kafka producer which will publish the messages based on the result of the cypher query. 

## How this feature can improve the project?
By adding this new feature we will be able to leverage all the advantages of having key in topic such as partitioning, order, log compaction, we can use the topic in joining multiple streams etc..

**Comment by Solom00n** [comment]
@KavitaUnified I think this would be really useful, not only for Neo4j Streams Procedures but also for Neo4j Streams Source and CDC. I opened an issue on this: see #305.

**Comment by moxious** [comment]
Adding to the roadmap, but this needs discussion on how best to approach it.  On one hand, all streams does is expose the payload sent by kafka.  Most people don't need the metadata, but the request to have it there has come up a number of times.   We need to consider a configurable option to turn this on.  I'm concerned we don't want it on by default because it'd result in sending lots of extra useless data through the wire on every transaction (for most use cases) but there's no doubt of a legitimate need for it in some cases.
