### ISSUE TITLE
[Discussion][CDC] Transfer the whole node info into every message

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-streams#315]
We can provide it as a `Source strategy` as we already planned to do with the key management.

/cc @moxious & David Fauth

**Comment by moxious** [comment]
@conker84 desired solution from talking with Dave:

Possible Solution

- Keep the producer data format the same, but add a few new keys:

Added: [prop1, prop2, prop3]
Changed: [prop4, prop5]
Deleted: [prop6]

- Do *not* publish the entire node properties every time, publish only what's stated in the pattern the user gave.  Because some properties may be very large, and this will cause a lot of unnecessary overhead if we "over-publish".   Users will sometimes write patterns that excludes a certain property because they know it's really heavy and they really don't want it sent out over the wire.
- When this payload arrives, change the sink Cypher to look at those fields, and then selectively update properties according to what happened
- Use the map merge trick to set the properties correctly at the end with += propertyBundle.  What I mean by this is let's say:

```
properties = { a: 1, b: 2 }
added = [a]
changed=[b]
deleted = [c]

This turns into finalProperties = { a: 1, b: 2, c: null }
Query then is n += finalProperties

And this will make the right change
```

- Provide a worked example in the docs on how to set this up end-to-end with a simple example.  We can steal Dave's example from the document I shared.   In particular, what config for the source, what config for the consumer to make this happen correctly end to end?

**Comment by conker84** [comment]
They are both breaking changes how should we handle this?
Because for the `source` there could be a consumer that uses the whole information. Moreover share the whole information about the data changes seems to be the standard behaviour for CDCs. Following an example of how Oracle Golden Gate works: (https://dzone.com/articles/creates-a-cdc-stream-from-oracle-database-to-kafka) 
Also for the `sink` because if there is no match between the versions of the sink and source there can be a problem on how the message is managed.

Do you think that a source strategy and a new sink strategy can be a possible solution for this?

**Comment by moxious** [comment]
On the production side, it seems to me it isn't a breaking change.  We are adding new keys to the payload being sent across, so that's backward compatible, right?  Older consumers won't use those payload keys, and that's no harm.

On the consumption side, it would be possible to add an extra config param, like for example:

```
streams.sink.topic.cdc.schema.to.gdstest=gds
streams.sink.topic.cdc.schema.to.gdstest.mode=(CHANGE|REPLACE)
```

I think Dave's case requires CHANGE, and the default behavior is REPLACE, which is really the difference between n = props and n += props.

These two different behaviors are tied to different assumptions:  is the CDC payload that's coming intended to say what the node is, or what has changed?

We could avoid a breaking change by keeping the default to be "REPLACE" but allowing "CHANGE".

**Comment by conker84** [comment]
> On the production side, it seems to me it isn't a breaking change. We are adding new keys to the payload being sent across, so that's backward compatible, right? Older consumers won't use those payload keys, and that's no harm.

There are two cases:
 - if we stop to publish the entire node properties is a breaking change because the user may have implemented his business rule leveraging the whole dataset;
 - if we add properties it should not be a breaking change unless it applied a `Structure` on his side (i.e. a simply Jackson config can blow up the deserialization), _but this scenario should be very remote_

> On the consumption side, it would be possible to add an extra config param, like for example:
> 
> ```
> streams.sink.topic.cdc.schema.to.gdstest=gds
> streams.sink.topic.cdc.schema.to.gdstest.mode=(CHANGE|REPLACE)
> ```
> 
> I think Dave's case requires CHANGE, and the default behavior is REPLACE, which is really the difference between n = props and n += props.
> 
> These two different behaviors are tied to different assumptions: is the CDC payload that's coming intended to say what the node is, or what has changed?
> 
> We could avoid a breaking change by keeping the default to be "REPLACE" but allowing "CHANGE".

Is it a problem if we create a new strategy?

`streams.sink.topic.cdc.schema-change.to.gdstest=gds`

So we can keep the two business logic separated.

**Comment by moxious** [comment]
We can create a separate strategy.   If at the end we have good guidance on how to configure to do this case, then it's fine.   On the other hand, it seems to me that we'd want to use CDC for replication between databases, and this issue leaves me wondering.... if we create a new strategy for this, then what use cases is the old strategy really answering?   I understand the desire not to break backwards compatibility, but it seems for a wide variety of reasonable things you'd want to do, the current strategy may not do the right thing.

Ultimately more strategies is OK, but they come at the cost of needing good documentation to describe how one is different than the other, and given examples.  Without this documentation & examples, more strategies is just harder to use / more confusion.

**Comment by conker84** [comment]
> We can create a separate strategy. If at the end we have good guidance on how to configure to do this case, then it's fine. On the other hand, it seems to me that we'd want to use CDC for replication between databases, and this issue leaves me wondering.... if we create a new strategy for this, then what use cases is the old strategy really answering? 

the goal of the old strategy was to provide 1:1 database replication, this means that the `source` and `sink` instance should have at the end of the stream the same dataset, the use case that we're trying to cover here is to append data (and we leverage the cypher `null` management in order to delete a property) to another instance by leveraging the CDC format.
For this reason, I think that if someone is already using it can feel lost if we change under-the-hood the behaviour.

> I understand the desire not to break backwards compatibility, but it seems for a wide variety of reasonable things you'd want to do, the current strategy may not do the right thing.
> 
> Ultimately more strategies is OK, but they come at the cost of needing good documentation to describe how one is different than the other, and given examples. Without this documentation & examples, more strategies is just harder to use / more confusion.

Yes I agree with you, this will become hard to document, and we should also provide different scenarios in order to the better explain we use each one.

**Comment by moxious** [comment]
In this case, let's go with a separate strategy. Perhaps call it replication.

**Comment by ali-ince** [comment]
Closing the discussion as we don't plan adding features to streams plugin.
