### ISSUE TITLE
Apache Pulsar support

### ISSUE THREAD

**Issue by elR1co** [neo4j-contrib/neo4j-streams#354]
It would be great if neo4j-streams plugin could support Apache Pulsar.

Is it something you could consider in the (near) future ?

Thanks a lot for the work done.

**Comment by moxious** [comment]
This would be a difficult one for us right now because of the resource commit necessary.  I'm keeping the issue open because I'd be particularly interested to see others +1 this over time to see what the demand signal for Pulsar would be.  We would consider it if there's a customer base of Neo4j users who need it.

**Comment by ali-ince** [comment]
Closing this as streams plugin is now deprecated and no future features are planned.
