### ISSUE TITLE
Allow multiple Cypher Statements for Sink

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-streams#95]
To have simpler cypher statements.
Execute in order.

```
streams.sink.cypher.topic.1=<statement1>
streams.sink.cypher.topic.2=<statement2>
```

**Comment by conker84** [comment]
Hi @vmantuano can you check if this issue fits your requirements?

**Comment by SAMBASIVA-TATIKONDA** [comment]
Team, Any timeline when this capability will be added?

**Comment by SAMBASIVA-TATIKONDA** [comment]
Michael,
With complex cypher requirements, mapping more than one cypher query for a single message is very critical and much needed feature to use this sink plugin. With lots of optional segments of the cypher query. We tried using WITH and OPTIONAL MATCH clauses to construct single cypher query. Unfortunately not all possible scenarios are getting covered. And also query maintenance became very difficult. We in-fact tried with apoc procedure apoc.cypher.runMany. It works on few scenarios. I am pretty sure, this capability is a great one and much needed one.

Could you please help on getting this issue fixed. Much appreciated your effort.

**Comment by SAMBASIVA-TATIKONDA** [comment]
Team,
Any timeline update on this issue? Thanks for your contributions.

**Comment by SAMBASIVA-TATIKONDA** [comment]
Andrea/Michael,

As i mentioned earlier, Writing a single cypher query for handling all the requirements around complex message data is really became lot of challenge for junior developers who are new to Cypher. Our Cypher queries for some of the topics hit almost 400-500 lines. We would love to break it into multiple queries at-least for each node & relationship merge behaviors

Could you please prioritize this issue. This is really very much needed enhancement for us. 
I am really thankful for your help and contributions.

**Comment by moxious** [comment]
@SAMBASIVA-TATIKONDA this feature is not a good option for this Kafka plugin, for several reasons which I would like to outline.   Before I get to those reasons, I want to point out your available alternatives, which is what I'd recommend instead.

1. Use KSQL to transform a stream from a complicated format to a simple format, enabling loading in 1 query and a very simple query.   https://docs.confluent.io/current/ksql/docs/developer-guide/transform-a-stream-with-ksql.html
2. If KSQL is not an option, then implement a Kafka connect worker, which would do the same thing -- transform the very complex input message into a simpler message that's the right format for you which can be ingested much more easily in Cypher https://gerardnico.com/dit/kafka/connect/worker
3. If you absolutely under no circumstances can change the input message format, then you can implement a custom Neo4j plugin in Java to process the message using Java instead of cypher.   Then, when you process the kafka method, your only cypher call is "CALL myProcedure(event)" and you're done, no multiple cypher calls necessary (the implementation if myProcedure can still do that if it's absolutely necessary)
4. Use APOC triggers to have your first defined neo4j-stream query trigger downstream queries (in the trigger) http://neo4j-contrib.github.io/neo4j-apoc-procedures/3.5/operational/triggers/

Your core issue is that if you find yourself writing hundreds of lines of cypher, you're trying to use Neo4j as an transformation engine for your data format.  That will be painful in the long run, becuase while cypher can do that, it's not its purpose.  This is equally not neo4j-stream's purpose.  This problem seems caused by the fact that your input data is probably the wrong format, and overly complex.  In the kafka architecture, typically people don't handle these extremely complicated problems at the endpoints (like Neo4j) you do it "on the wire" by transforming the messages to something simpler.

There are several reasons why the specific feature you're asking for isn't a good idea.

1. It makes neo4j-streams into a workflow engine with support for only a straight line "pipeline" of queries.  When you try to make complicated workflows to do your ETL in the database, pretty soon you will find yourself needing conditionals between these queries and an even more complex workflow, because you're trying to do ETL in the database.
2. There is no transaction dependence between the queries.  What should happen if you define 3 queries, and number 1 and 3 fails, but 2 succeeds?  Your database is left in a bad state, and there's no way to get back.  Breaking into multiple queries makes multiple transactions, which breaks you out of the ACID guarantees the database should give you.
3. Because we need to get you to put the cypher into a configuration file, I'm sure you've already seen that it's difficult to edit big complex cypher in a configuration file, particularly when it's hundreds of lines long.   Adding a pipeline of multiple queries only allows you to make this management problem more painful.

I would urge you to rethink your approach to this problem and pick one of the alternative implementation approaches I suggest.

**Comment by tankawesome** [comment]
> @SAMBASIVA-TATIKONDA this feature is not a good option for this Kafka plugin, for several reasons which I would like to outline. Before I get to those reasons, I want to point out your available alternatives, which is what I'd recommend instead.
> 
> 1. Use KSQL to transform a stream from a complicated format to a simple format, enabling loading in 1 query and a very simple query.   https://docs.confluent.io/current/ksql/docs/developer-guide/transform-a-stream-with-ksql.html
> 2. If KSQL is not an option, then implement a Kafka connect worker, which would do the same thing -- transform the very complex input message into a simpler message that's the right format for you which can be ingested much more easily in Cypher https://gerardnico.com/dit/kafka/connect/worker
> 3. If you absolutely under no circumstances can change the input message format, then you can implement a custom Neo4j plugin in Java to process the message using Java instead of cypher.   Then, when you process the kafka method, your only cypher call is "CALL myProcedure(event)" and you're done, no multiple cypher calls necessary (the implementation if myProcedure can still do that if it's absolutely necessary)
> 4. Use APOC triggers to have your first defined neo4j-stream query trigger downstream queries (in the trigger) http://neo4j-contrib.github.io/neo4j-apoc-procedures/3.5/operational/triggers/
> 
> (If I was you I would most likely choose option 3)
> 
> Your core issue is that if you find yourself writing hundreds of lines of cypher, you're trying to use Neo4j as an transformation engine for your data format. That will be painful in the long run, because while cypher can do that, it's not its purpose. This is equally not neo4j-stream's purpose; it is not trying to let users define a cypher workflow, it's trying to make it easy to trigger cypher events from input messages. This problem seems caused by the fact that your input data is probably the wrong format, and overly complex considering what you want in Neo4j. In the kafka architecture, typically people don't handle these extremely complicated problems at the endpoints (like Neo4j) you do it "on the wire" by transforming the messages to something simpler.
> 
> There are several reasons why the specific feature you're asking for isn't a good idea for this code base. If we were to implement it, I think it would make your system more difficult to deal with over time, because:
> 
> 1. It makes neo4j-streams into a workflow engine with support for only a straight line "pipeline" of queries.  When you try to make complicated workflows to do your ETL in the database, pretty soon you will find yourself needing conditionals between these queries and an even more complex workflow, because you're trying to do ETL in the database.
> 2. There is no transaction dependence between the queries.  What should happen if you define 3 queries, and number 1 and 3 fails, but 2 succeeds?  Your database is left in a bad state, and there's no way to get back.  Breaking into multiple queries makes multiple transactions, which breaks you out of the ACID guarantees the database should give you.
> 3. Because we need to get you to put the cypher into a configuration file, I'm sure you've already seen that it's difficult to edit big complex cypher in a configuration file, particularly when it's hundreds of lines long.   Adding a pipeline of multiple queries only allows you to make this management problem more painful.
> 
> I would urge you to rethink your approach to this problem and pick one of the alternative implementation approaches I suggest.

Could you expand on how to implement the java option?  I am having trouble finding documentation on passing entire events from the stream to java.  Would you implement this as a procedure?  Or a function?  Any help would be greatly appreciated!
